events {}

http {
  server_tokens off;

  server {
    listen 443 ssl;
    server_name garage-proxy;

    ssl_certificate /run/secrets/storage_tls_certificate;
    ssl_certificate_key /run/secrets/storage_tls_private_key;
    ssl_protocols TLSv1.2 TLSv1.3;

    client_max_body_size 32m;
    proxy_request_buffering off;
    proxy_buffering off;

    location / {
      proxy_pass http://garage:3900;
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-Proto https;
    }
  }
}
