from django.urls import path

from medical.views import (
    DocumentAudioUploadView,
    CaptureTranscriptionView,
    NoteProcessView,
    DocumentDetailView,
    DocumentExplanationRegenerateView,
    DocumentExplanationView,
    DocumentIngestView,
    DocumentListCreateView,
    EventDetailView,
    EventListCreateView,
    EventSearchView,
    JobDetailView,
    SummaryCurrentView,
    SummaryExportView,
    SummaryRegenerateView,
    SummaryVersionsView,
    SubjectDetailView,
    SubjectListCreateView,
    TimelineView,
    VisitPreparationView,
)

urlpatterns = [
    path("subjects", SubjectListCreateView.as_view(), name="subject-list"),
    path("subjects/<uuid:id>", SubjectDetailView.as_view(), name="subject-detail"),
    path("documents", DocumentListCreateView.as_view(), name="document-list"),
    path("documents/upload-audio", DocumentAudioUploadView.as_view(), name="document-upload-audio"),
    path("capture/transcribe", CaptureTranscriptionView.as_view(), name="capture-transcribe"),
    path("capture/notes", NoteProcessView.as_view(), name="capture-note-process"),
    path("documents/<uuid:id>", DocumentDetailView.as_view(), name="document-detail"),
    path("documents/<uuid:id>/ingest", DocumentIngestView.as_view(), name="document-ingest"),
    path("documents/<uuid:id>/explanation", DocumentExplanationView.as_view(), name="document-explanation"),
    path(
        "documents/<uuid:id>/explanation/regenerate",
        DocumentExplanationRegenerateView.as_view(),
        name="document-explanation-regenerate",
    ),
    path("events", EventListCreateView.as_view(), name="event-list"),
    path("events/search", EventSearchView.as_view(), name="event-search"),
    path("events/<uuid:id>", EventDetailView.as_view(), name="event-detail"),
    path("timeline", TimelineView.as_view(), name="timeline"),
    path("summary", SummaryCurrentView.as_view(), name="summary-current"),
    path("summary/regenerate", SummaryRegenerateView.as_view(), name="summary-regenerate"),
    path("summary/versions", SummaryVersionsView.as_view(), name="summary-versions"),
    path("summary/export", SummaryExportView.as_view(), name="summary-export"),
    path("visit-preparation", VisitPreparationView.as_view(), name="visit-preparation"),
    path("jobs/<uuid:id>", JobDetailView.as_view(), name="job-detail"),
]
