# Generated by Django 5.1.15 on 2026-06-26 19:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255)),
                ('relationship', models.CharField(choices=[('self', 'Self'), ('child', 'Child'), ('dependent', 'Dependent'), ('other', 'Other')], default='self', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('biological_sex', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male')], max_length=20, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-is_default', 'display_name'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MedicalEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('symptom', 'Symptom'), ('diagnosis', 'Diagnosis'), ('medication', 'Medication'), ('examination', 'Examination'), ('procedure', 'Procedure'), ('hospitalization', 'Hospitalization'), ('treatment_outcome', 'Treatment outcome'), ('note', 'Note')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField()),
                ('event_end_date', models.DateField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(choices=[('user_manual', 'User manual'), ('ai_document', 'AI document'), ('ai_voice', 'AI voice')], default='user_manual', max_length=30)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_events', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_events', to='medical.subject')),
                ('tags', models.ManyToManyField(blank=True, related_name='medical_events', to='medical.tag')),
            ],
            options={
                'ordering': ('-event_date', '-created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_subject_per_user'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_tag_name_per_user'),
        ),
        migrations.AddIndex(
            model_name='medicalevent',
            index=models.Index(fields=['user', 'subject', '-event_date'], name='event_user_subject_date_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalevent',
            index=models.Index(fields=['event_type'], name='event_type_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalevent',
            index=models.Index(fields=['deleted_at'], name='event_deleted_at_idx'),
        ),
    ]
