# Generated by Codex on 2026-06-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0002_document_medicalevent_source_document_processingjob_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("medical_record", "Medical record"),
                    ("lab_result", "Lab result"),
                    ("report", "Report"),
                    ("prescription", "Prescription"),
                    ("procedure_summary", "Procedure summary"),
                    ("note", "Note"),
                    ("image", "Image"),
                    ("audio", "Audio"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
