# Generated by Codex on 2026-06-28

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0003_add_medical_record_document_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processingjob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("ingestion", "Ingestion"),
                    ("explanation", "Explanation"),
                ],
                default="ingestion",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="DocumentExplanation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("summary_text", models.TextField()),
                ("key_points", models.JSONField(blank=True, default=list)),
                ("glossary", models.JSONField(blank=True, default=dict)),
                ("model_name", models.CharField(max_length=255)),
                ("language", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="explanations",
                        to="medical.document",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="documentexplanation",
            index=models.Index(fields=["document", "-created_at"], name="expl_doc_created_idx"),
        ),
        migrations.AddIndex(
            model_name="documentexplanation",
            index=models.Index(fields=["language"], name="expl_language_idx"),
        ),
    ]
