# Generated by Codex on 2026-07-03

import uuid

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("medical", "0004_document_explanation"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalSummary",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.PositiveIntegerField()),
                ("is_current", models.BooleanField(default=True)),
                ("content", models.JSONField(default=dict)),
                ("narrative_text", models.TextField()),
                ("generated_from_event_count", models.PositiveIntegerField(default=0)),
                ("model_name", models.CharField(max_length=255)),
                ("language", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_summaries",
                        to="medical.subject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AlterField(
            model_name="processingjob",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="processing_jobs",
                to="medical.document",
            ),
        ),
        migrations.AlterField(
            model_name="processingjob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("ingestion", "Ingestion"),
                    ("explanation", "Explanation"),
                    ("summary", "Summary"),
                ],
                default="ingestion",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="processingjob",
            name="summary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processing_jobs",
                to="medical.medicalsummary",
            ),
        ),
        migrations.AddIndex(
            model_name="medicalsummary",
            index=models.Index(fields=["user", "subject", "-created_at"], name="summary_user_subject_idx"),
        ),
        migrations.AddIndex(
            model_name="medicalsummary",
            index=models.Index(fields=["is_current"], name="summary_is_current_idx"),
        ),
        migrations.AddConstraint(
            model_name="medicalsummary",
            constraint=models.UniqueConstraint(fields=("subject", "version"), name="unique_summary_version_per_subject"),
        ),
        migrations.AddConstraint(
            model_name="medicalsummary",
            constraint=models.UniqueConstraint(
                condition=models.Q(is_current=True),
                fields=("subject",),
                name="unique_current_summary_per_subject",
            ),
        ),
    ]
