# Generated by Django 5.0.6 on 2026-07-13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical", "0010_remove_medicalevent_is_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="content_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["user", "content_hash"],
                name="document_user_hash_idx",
            ),
        ),
    ]
