# Generated by Django 5.1.15 on 2026-07-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0011_document_content_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('account_delete', 'Account delete')], max_length=50),
        ),
    ]
