# Generated by Django 5.1.15 on 2026-07-28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0015_appointment_preparation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EncryptedBlob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_key", models.CharField(max_length=255, unique=True)),
                ("encrypted_key", models.BinaryField()),
                ("master_key_version", models.PositiveIntegerField(default=1)),
                (
                    "encryption_format",
                    models.CharField(default="aws-esdk-v1", max_length=50),
                ),
                ("fingerprint", models.CharField(max_length=64)),
                ("plaintext_size", models.BigIntegerField()),
                ("ciphertext_size", models.BigIntegerField()),
                ("reference_count", models.PositiveIntegerField(default=1)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("deletion_pending", "Deletion pending"),
                        ],
                        default="available",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encrypted_blobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StorageDeletionJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_key", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"ordering": ("created_at",)},
        ),
        migrations.RemoveField(
            model_name="consentdecision",
            name="user",
        ),
        migrations.RemoveField(
            model_name="productanalyticsevent",
            name="user",
        ),
        migrations.RemoveConstraint(
            model_name="processingjob",
            name="unique_active_summary_input",
        ),
        migrations.RemoveIndex(
            model_name="processingjob",
            name="job_user_input_idx",
        ),
        migrations.RemoveField(
            model_name="documentasset",
            name="content_hash",
        ),
        migrations.RemoveField(
            model_name="medicalsummary",
            name="approval_status",
        ),
        migrations.RemoveField(
            model_name="medicalsummary",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="processingjob",
            name="input_fingerprint",
        ),
        migrations.RemoveField(
            model_name="processingjob",
            name="subject",
        ),
        migrations.AddField(
            model_name="documentasset",
            name="is_transient",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="documentasset",
            name="blob",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="document_assets",
                to="medical.encryptedblob",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("account_delete", "Account delete"),
                    ("original_open", "Original open"),
                    ("original_download", "Original download"),
                    ("original_delete", "Original delete"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="storagedeletionjob",
            index=models.Index(
                fields=["status", "created_at"],
                name="storage_delete_status_idx",
            ),
        ),
        migrations.DeleteModel(
            name="ConsentDecision",
        ),
        migrations.DeleteModel(
            name="ProductAnalyticsEvent",
        ),
        migrations.AddIndex(
            model_name="encryptedblob",
            index=models.Index(
                fields=["user", "state"],
                name="blob_user_state_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="encryptedblob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "available")),
                fields=("user", "fingerprint"),
                name="unique_encrypted_blob_fingerprint_per_user",
            ),
        ),
    ]
